"""add learning contexts

Revision ID: ab4e8117e138
Revises: e5c2f7102456
Create Date: 2026-09-18 19:34:33.820726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4e8117e138'
down_revision: Union[str, Sequence[str], None] = 'e5c2f7102456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('repeated_mistakes', sa.JSON(), nullable=True),
    sa.Column('important_history', sa.JSON(), nullable=True),
    sa.Column('assessment_summary', sa.JSON(), nullable=True),
    sa.Column('tutor_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_contexts_id'), 'learning_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_learning_contexts_project_id'), 'learning_contexts', ['project_id'], unique=True)
    op.create_index(op.f('ix_learning_contexts_user_id'), 'learning_contexts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_contexts_user_id'), table_name='learning_contexts')
    op.drop_index(op.f('ix_learning_contexts_project_id'), table_name='learning_contexts')
    op.drop_index(op.f('ix_learning_contexts_id'), table_name='learning_contexts')
    op.drop_table('learning_contexts')
    # ### end Alembic commands ###
