"""add learning events

Revision ID: e5c2f7102456
Revises: fefe267feace
Create Date: 2026-09-18 19:16:16.915935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c2f7102456'
down_revision: Union[str, Sequence[str], None] = 'fefe267feace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_events_created_at'), 'learning_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_learning_events_event_type'), 'learning_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_learning_events_id'), 'learning_events', ['id'], unique=False)
    op.create_index(op.f('ix_learning_events_project_id'), 'learning_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_learning_events_space_id'), 'learning_events', ['space_id'], unique=False)
    op.create_index(op.f('ix_learning_events_user_id'), 'learning_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_events_user_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_space_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_project_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_event_type'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_created_at'), table_name='learning_events')
    op.drop_table('learning_events')
    # ### end Alembic commands ###
