"""add mastery and growth

Revision ID: fefe267feace
Revises: 60c25f9cf7a9
Create Date: 2026-09-18 17:00:16.599450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fefe267feace'
down_revision: Union[str, Sequence[str], None] = '60c25f9cf7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_mastery_concept'), 'concept_mastery', ['concept'], unique=False)
    op.create_index(op.f('ix_concept_mastery_id'), 'concept_mastery', ['id'], unique=False)
    op.create_index(op.f('ix_concept_mastery_project_id'), 'concept_mastery', ['project_id'], unique=False)
    op.create_table('mastery_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('new_score', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mastery_snapshots_attempt_id'), 'mastery_snapshots', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_mastery_snapshots_concept'), 'mastery_snapshots', ['concept'], unique=False)
    op.create_index(op.f('ix_mastery_snapshots_id'), 'mastery_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_mastery_snapshots_project_id'), 'mastery_snapshots', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mastery_snapshots_project_id'), table_name='mastery_snapshots')
    op.drop_index(op.f('ix_mastery_snapshots_id'), table_name='mastery_snapshots')
    op.drop_index(op.f('ix_mastery_snapshots_concept'), table_name='mastery_snapshots')
    op.drop_index(op.f('ix_mastery_snapshots_attempt_id'), table_name='mastery_snapshots')
    op.drop_table('mastery_snapshots')
    op.drop_index(op.f('ix_concept_mastery_project_id'), table_name='concept_mastery')
    op.drop_index(op.f('ix_concept_mastery_id'), table_name='concept_mastery')
    op.drop_index(op.f('ix_concept_mastery_concept'), table_name='concept_mastery')
    op.drop_table('concept_mastery')
    # ### end Alembic commands ###
